"""Email Deliverability — audit and repair SPF, DKIM and DMARC for a domain.

cPanel's "Email Deliverability" tool. For each domain the account owns it checks
the three DNS records that make outgoing mail trusted, and offers a one-click
repair that installs any that are missing.

The panel DB is the source of truth for DNS (see routers/dns.py), so a repair is
just adding the missing TXT records and re-syncing the zone:

  * SPF   — TXT at the apex starting `v=spf1` (which servers may send our mail).
  * DMARC — TXT at `_dmarc` starting `v=DMARC1` (what to do with failing mail).
  * DKIM  — TXT at `default._domainkey` holding a public key. The keypair is
            generated by the provider; the private half is stored on the host
            and registered with opendkim, so outgoing mail is signed with it
            as soon as the record is published.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from ..db import get_db
from ..models import DnsRecord, Domain, User
from ..providers import get_provider
from ..security import current_user
from ..web import templates
from .dns import _seed_defaults, _sync

router = APIRouter(prefix="/deliverability", tags=["deliverability"])

SPF_RECOMMENDED = "v=spf1 +mx +a ~all"
DMARC_HOST = "_dmarc"
DMARC_RECOMMENDED = "v=DMARC1; p=none;"
DKIM_HOST = "default._domainkey"


def _flash(request: Request, message: str) -> None:
    request.session["flash"] = message


def _txt_at(records: list[DnsRecord], host: str) -> list[DnsRecord]:
    """TXT records whose host name matches (case-insensitive; '@' = apex)."""
    return [r for r in records if r.rtype == "TXT" and (r.name or "@").lower() == host.lower()]


def _one(found: list[DnsRecord], recommended: str, host: str, kind: str) -> dict:
    """Status of a single mechanism from the matching records."""
    if not found:
        return {"status": "missing", "current": None, "recommended": recommended,
                "host": host, "note": None}
    note = None
    if len(found) > 1:
        note = f"{len(found)} {kind} records found — there should be exactly one."
        status = "warning"
    else:
        status = "valid"
    return {"status": status, "current": found[0].value, "recommended": recommended,
            "host": host, "note": note}


def _audit(records: list[DnsRecord]) -> dict:
    spf = [r for r in _txt_at(records, "@") if r.value.lower().startswith("v=spf1")]
    dmarc = [r for r in _txt_at(records, DMARC_HOST) if r.value.lower().startswith("v=dmarc1")]
    dkim = [r for r in _txt_at(records, DKIM_HOST) if "v=dkim1" in r.value.lower()]
    return {
        "spf": _one(spf, SPF_RECOMMENDED, "@", "SPF"),
        "dkim": _one(dkim, "(a key is generated when you install)", DKIM_HOST, "DKIM"),
        "dmarc": _one(dmarc, DMARC_RECOMMENDED, DMARC_HOST, "DMARC"),
    }


@router.get("")
def deliverability(
    request: Request,
    domain_id: int | None = None,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
):
    domains = db.scalars(
        select(Domain).where(Domain.owner_id == user.id).order_by(Domain.name)
    ).all()
    flash = request.session.pop("flash", None)
    ctx = {"user": user, "domains": domains, "active": "deliverability", "flash": flash,
           "selected": None, "audit": None, "all_valid": False}

    if domains:
        selected = db.get(Domain, domain_id) if domain_id else domains[0]
        if selected is None or selected.owner_id != user.id:
            selected = domains[0]
        records = db.scalars(
            select(DnsRecord).where(DnsRecord.domain_id == selected.id)
        ).all()
        audit = _audit(records)
        ctx.update({"selected": selected, "audit": audit,
                    "all_valid": all(a["status"] == "valid" for a in audit.values())})

    return templates.TemplateResponse(request, "deliverability.html", ctx)


@router.post("/{domain_id}/repair")
def repair(
    request: Request,
    domain_id: int,
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
):
    domain = db.get(Domain, domain_id)
    if domain is None or domain.owner_id != user.id:
        _flash(request, "❌ Domain not found.")
        return RedirectResponse("/deliverability", status_code=303)

    # A zone with no records at all has never been opened — lay down the cPanel
    # starter set (A/MX/SPF) first so we're not publishing DMARC/DKIM onto an
    # otherwise-empty zone.
    if not domain.dns_records:
        _seed_defaults(db, domain)

    records = db.scalars(select(DnsRecord).where(DnsRecord.domain_id == domain.id)).all()
    audit = _audit(records)
    added: list[str] = []

    if audit["spf"]["status"] == "missing":
        db.add(DnsRecord(domain_id=domain.id, rtype="TXT", name="@", value=SPF_RECOMMENDED))
        added.append("SPF")
    if audit["dmarc"]["status"] == "missing":
        db.add(DnsRecord(domain_id=domain.id, rtype="TXT", name=DMARC_HOST, value=DMARC_RECOMMENDED))
        added.append("DMARC")
    if audit["dkim"]["status"] == "missing":
        try:
            _selector, txt = get_provider().generate_dkim(domain.name)
        except Exception as exc:  # noqa: BLE001 — surface a friendly reason, not a 500
            _flash(request, f"❌ Could not generate a DKIM key: {exc}")
            return RedirectResponse(f"/deliverability?domain_id={domain_id}", status_code=303)
        db.add(DnsRecord(domain_id=domain.id, rtype="TXT", name=DKIM_HOST, value=txt))
        added.append("DKIM")

    db.commit()
    _sync(db, domain)

    if added:
        _flash(request, f"✅ Installed {', '.join(added)} record(s) for {domain.name}. "
                        "If this domain uses external DNS, copy the values there too.")
    else:
        _flash(request, f"✅ SPF, DKIM and DMARC are already present for {domain.name}.")
    return RedirectResponse(f"/deliverability?domain_id={domain_id}", status_code=303)
