"""wordpress subdirectory install path

Revision ID: 8e6db64bebf2
Revises: 41eddda7dc7e
Create Date: 2026-07-29 19:38:35.028018
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6db64bebf2'
down_revision: Union[str, None] = '41eddda7dc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=64), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_apps', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
