"""add domain.force_https

Revision ID: 7addb2a2f9de
Revises: 90545cf716dc
Create Date: 2026-07-29 07:36:22.820576
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7addb2a2f9de'
down_revision: Union[str, None] = '90545cf716dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        # server_default so existing rows get a value (SQLite can't add a bare
        # NOT NULL column to a table that already has rows).
        batch_op.add_column(sa.Column('force_https', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_column('force_https')

    # ### end Alembic commands ###
