"""wp uninstall db_name + db password for pma autologin

Revision ID: 41eddda7dc7e
Revises: 4ff18a54cd34
Create Date: 2026-07-29 19:06:38.276840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41eddda7dc7e'
down_revision: Union[str, None] = '4ff18a54cd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('databases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('db_password_enc', sa.String(length=255), nullable=True))

    with op.batch_alter_table('wordpress_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('db_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_apps', schema=None) as batch_op:
        batch_op.drop_column('db_name')

    with op.batch_alter_table('databases', schema=None) as batch_op:
        batch_op.drop_column('db_password_enc')

    # ### end Alembic commands ###
