"""add wordpress_apps

Revision ID: 4ff18a54cd34
Revises: 7addb2a2f9de
Create Date: 2026-07-29 12:58:31.190713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff18a54cd34'
down_revision: Union[str, None] = '7addb2a2f9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordpress_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('admin_user', sa.String(length=64), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('login_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordpress_apps')
    # ### end Alembic commands ###
