"""add packages and user.package_id

Revision ID: 1e146c1080e6
Revises: 9b7223035186
Create Date: 2026-07-28 11:40:03.994954
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e146c1080e6'
down_revision: Union[str, None] = '9b7223035186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('max_domains', sa.Integer(), nullable=False),
    sa.Column('max_databases', sa.Integer(), nullable=False),
    sa.Column('max_email', sa.Integer(), nullable=False),
    sa.Column('disk_quota_mb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_package_owner_name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_package_id', 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_package_id', type_='foreignkey')
        batch_op.drop_column('package_id')

    op.drop_table('packages')
    # ### end Alembic commands ###
